### PR TITLE
Add example for using inside a module

### PR DESCRIPTION
**Pull request by wesbos**
Trying to use this inside a npx script, so I can't set the env variables (at least I don't know how!).

Figured out this little trick. Not sure it's ideal for larger apps, but worked great!

### CODE REVIEW

**Comment by dword-design** [comment]
Why can't you use this?

```js
import 'suppress-experimental-warnings';

import './your-app.js';
```

**Comment by wesbos** [comment]
It didn't work. I think because the require of the fix needs to happen before the require of the module that causes a warning. Using the await import() will put the import on the next tick / end of the event loop.

I am using it like this:

your-app.js:

```js
import pkg from './package.json' assert { type: "json" };
console.log(pkg);
```

Then the start script:

```js
import 'suppress-experimental-warnings';
await import('./your-app.js');
```

node -r does the same thing where it requires a package first before it loads the next one.

**Comment by dword-design** [comment]
@wesbos Looks like the import order is currently non-deterministic, so it makes sense to document it like you did. Thanks for contributing!

**Comment by wesbos** [comment]
no problem! Thanks for the package: )

**Pull request merged**
